services:
  - type: web
    name: texas4win-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app_flask --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: BOT_TOKEN
        value: 8624354425:AAEYNe5BOSlFNoC-X0SpTCTwNnRre_SMsZE
      - key: OWNER_IDS
        value: 6693251012
      - key: ADMIN_GROUP
        value: -1003983996094
      - key: AGENT_USERNAME
        value: Bero@yahoo.com
      - key: AGENT_PASSWORD
        value: Aazzam@318
      - key: PARENT_ID
        value: 2688288
      - key: CURRENCY
        value: SYP
      - key: SHAM_CASH_WALLET
        value: a18758d5324eb7595d4463ca355ad221
      - key: SYRIATEL_CASH_CODE
        value: 48122120
      - key: DEPOSIT_MIN
        value: 100000
      - key: WITHDRAW_MIN
        value: 200000
      - key: WITHDRAW_MAX
        value: 2000000
      - key: WITHDRAW_FEE_PERCENT
        value: 10
      - key: API_BASE
        value: https://agents.texas4win.com/global/api/User/
      - key: WEBHOOK_URL
        value: https://bahr-bot-c3ac.onrender.com/webhook
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
